<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Colmado.Application\Colmado.Application.csproj" />
    <ProjectReference Include="..\Colmado.Infrastructure\Colmado.Infrastructure.csproj" />
    <ProjectReference Include="..\Colmado.Domain\Colmado.Domain.csproj" />
  </ItemGroup>

</Project>
